In [5]:
import numpy as np
x=np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


In [6]:
print(np.where(x==13))

(array([3], dtype=int64),)


In [7]:

print(x.tolist().index(13))

3


In [8]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
print(x[x==13])

[13]


In [10]:
k=0
for a in x:
    if(a==13):
     print(k)
    k+=1

3


In [11]:
v=[1,2,3,5,7,8,9]
print(v.index(9))

6


In [17]:
#Selecting specific rows and columns from NumPy array
a = np.arange(20).reshape((5,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
print (a[[0,1,3], [0,2]])
# solve is given below

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [14]:
a[[[0], [1], [3]], [0, 2]]

array([[ 0,  2],
       [ 4,  6],
       [12, 14]])

In [19]:
a[[0,1,3], :][:, [0,2]] 

array([[ 0,  2],
       [ 4,  6],
       [12, 14]])

In [20]:
a[np.ix_([0,1,3], [0,2])]

array([[ 0,  2],
       [ 4,  6],
       [12, 14]])

In [21]:
 a[[0,1,3]][:,[0,2]]

array([[ 0,  2],
       [ 4,  6],
       [12, 14]])